23=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x3
24=HOOK MAIN
25=BIND MAIN
26=SAVE conv2d_tf
27=WIDTH MAIN.w
28=HEIGHT MAIN.h
29=COMPONENTS 4
30=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
45=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x8
46=HOOK MAIN
47=BIND conv2d_tf
48=SAVE conv2d_1_tf
49=WIDTH conv2d_tf.w
50=HEIGHT conv2d_tf.h
51=COMPONENTS 4
52=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
77=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x8
78=HOOK MAIN
79=BIND conv2d_1_tf
80=SAVE conv2d_2_tf
81=WIDTH conv2d_1_tf.w
82=HEIGHT conv2d_1_tf.h
83=COMPONENTS 4
84=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
109=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x8
110=HOOK MAIN
111=BIND conv2d_2_tf
112=SAVE conv2d_3_tf
113=WIDTH conv2d_2_tf.w
114=HEIGHT conv2d_2_tf.h
115=COMPONENTS 4
116=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
141=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x8
142=HOOK MAIN
143=BIND conv2d_3_tf
144=SAVE conv2d_4_tf
145=WIDTH conv2d_3_tf.w
146=HEIGHT conv2d_3_tf.h
147=COMPONENTS 4
148=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
173=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x8
174=HOOK MAIN
175=BIND conv2d_4_tf
176=SAVE conv2d_5_tf
177=WIDTH conv2d_4_tf.w
178=HEIGHT conv2d_4_tf.h
179=COMPONENTS 4
180=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
205=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x3x3x8
206=HOOK MAIN
207=BIND conv2d_5_tf
208=SAVE conv2d_6_tf
209=WIDTH conv2d_5_tf.w
210=HEIGHT conv2d_5_tf.h
211=COMPONENTS 4
212=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
237=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Conv-4x1x1x56
238=HOOK MAIN
239=BIND conv2d_tf
240=BIND conv2d_1_tf
241=BIND conv2d_2_tf
242=BIND conv2d_3_tf
243=BIND conv2d_4_tf
244=BIND conv2d_5_tf
245=BIND conv2d_6_tf
246=SAVE conv2d_last_tf
247=WIDTH conv2d_tf.w
248=HEIGHT conv2d_tf.h
249=COMPONENTS 4
250=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
283=DESC Anime4K-v3.2-Upscale-CNN-x2-(M)-Depth-to-Space
284=HOOK MAIN
285=BIND MAIN
286=BIND conv2d_last_tf
287=SAVE MAIN
288=WIDTH conv2d_last_tf.w 2 *
289=HEIGHT conv2d_last_tf.h 2 *
290=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
