23=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x3
24=HOOK MAIN
25=BIND MAIN
26=SAVE conv2d_tf
27=WIDTH MAIN.w
28=HEIGHT MAIN.h
29=COMPONENTS 4
44=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x8
45=HOOK MAIN
46=BIND conv2d_tf
47=SAVE conv2d_1_tf
48=WIDTH conv2d_tf.w
49=HEIGHT conv2d_tf.h
50=COMPONENTS 4
75=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x8
76=HOOK MAIN
77=BIND conv2d_1_tf
78=SAVE conv2d_2_tf
79=WIDTH conv2d_1_tf.w
80=HEIGHT conv2d_1_tf.h
81=COMPONENTS 4
106=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x8
107=HOOK MAIN
108=BIND conv2d_2_tf
109=SAVE conv2d_3_tf
110=WIDTH conv2d_2_tf.w
111=HEIGHT conv2d_2_tf.h
112=COMPONENTS 4
137=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x8
138=HOOK MAIN
139=BIND conv2d_3_tf
140=SAVE conv2d_4_tf
141=WIDTH conv2d_3_tf.w
142=HEIGHT conv2d_3_tf.h
143=COMPONENTS 4
168=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x8
169=HOOK MAIN
170=BIND conv2d_4_tf
171=SAVE conv2d_5_tf
172=WIDTH conv2d_4_tf.w
173=HEIGHT conv2d_4_tf.h
174=COMPONENTS 4
199=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-4x3x3x8
200=HOOK MAIN
201=BIND conv2d_5_tf
202=SAVE conv2d_6_tf
203=WIDTH conv2d_5_tf.w
204=HEIGHT conv2d_5_tf.h
205=COMPONENTS 4
230=DESC Anime4K-v4.0-Restore-CNN-(M)-Conv-3x1x1x56
231=HOOK MAIN
232=BIND MAIN
233=BIND conv2d_tf
234=BIND conv2d_1_tf
235=BIND conv2d_2_tf
236=BIND conv2d_3_tf
237=BIND conv2d_4_tf
238=BIND conv2d_5_tf
239=BIND conv2d_6_tf
240=SAVE MAIN
241=WIDTH conv2d_tf.w
242=HEIGHT conv2d_tf.h
