25=DESC Anime4K-v4.0-AutoDownscalePre-x2
26=HOOK MAIN
27=BIND HOOKED
28=BIND NATIVE
29=WHEN OUTPUT.w NATIVE.w / 2.0 < OUTPUT.h NATIVE.h / 2.0 < * OUTPUT.w NATIVE.w / 1.2 > OUTPUT.h NATIVE.h / 1.2 > * *
30=WIDTH OUTPUT.w
31=HEIGHT OUTPUT.h
