23=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x3
24=HOOK MAIN
25=BIND MAIN
26=SAVE conv2d_tf
27=WIDTH MAIN.w
28=HEIGHT MAIN.h
29=COMPONENTS 4
44=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x3
45=HOOK MAIN
46=BIND MAIN
47=SAVE conv2d_tf1
48=WIDTH MAIN.w
49=HEIGHT MAIN.h
50=COMPONENTS 4
65=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
66=HOOK MAIN
67=BIND conv2d_tf
68=BIND conv2d_tf1
69=SAVE conv2d_1_tf
70=WIDTH conv2d_tf.w
71=HEIGHT conv2d_tf.h
72=COMPONENTS 4
117=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
118=HOOK MAIN
119=BIND conv2d_tf
120=BIND conv2d_tf1
121=SAVE conv2d_1_tf1
122=WIDTH conv2d_tf.w
123=HEIGHT conv2d_tf.h
124=COMPONENTS 4
169=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
170=HOOK MAIN
171=BIND conv2d_1_tf
172=BIND conv2d_1_tf1
173=SAVE conv2d_2_tf
174=WIDTH conv2d_1_tf.w
175=HEIGHT conv2d_1_tf.h
176=COMPONENTS 4
221=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
222=HOOK MAIN
223=BIND conv2d_1_tf
224=BIND conv2d_1_tf1
225=SAVE conv2d_2_tf1
226=WIDTH conv2d_1_tf.w
227=HEIGHT conv2d_1_tf.h
228=COMPONENTS 4
273=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
274=HOOK MAIN
275=BIND conv2d_2_tf
276=BIND conv2d_2_tf1
277=SAVE conv2d_3_tf
278=WIDTH conv2d_2_tf.w
279=HEIGHT conv2d_2_tf.h
280=COMPONENTS 4
325=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
326=HOOK MAIN
327=BIND conv2d_2_tf
328=BIND conv2d_2_tf1
329=SAVE conv2d_3_tf1
330=WIDTH conv2d_2_tf.w
331=HEIGHT conv2d_2_tf.h
332=COMPONENTS 4
377=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
378=HOOK MAIN
379=BIND conv2d_3_tf
380=BIND conv2d_3_tf1
381=SAVE conv2d_4_tf
382=WIDTH conv2d_3_tf.w
383=HEIGHT conv2d_3_tf.h
384=COMPONENTS 4
429=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
430=HOOK MAIN
431=BIND conv2d_3_tf
432=BIND conv2d_3_tf1
433=SAVE conv2d_4_tf1
434=WIDTH conv2d_3_tf.w
435=HEIGHT conv2d_3_tf.h
436=COMPONENTS 4
481=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
482=HOOK MAIN
483=BIND conv2d_4_tf
484=BIND conv2d_4_tf1
485=SAVE conv2d_5_tf
486=WIDTH conv2d_4_tf.w
487=HEIGHT conv2d_4_tf.h
488=COMPONENTS 4
533=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
534=HOOK MAIN
535=BIND conv2d_4_tf
536=BIND conv2d_4_tf1
537=SAVE conv2d_5_tf1
538=WIDTH conv2d_4_tf.w
539=HEIGHT conv2d_4_tf.h
540=COMPONENTS 4
585=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
586=HOOK MAIN
587=BIND conv2d_5_tf
588=BIND conv2d_5_tf1
589=SAVE conv2d_6_tf
590=WIDTH conv2d_5_tf.w
591=HEIGHT conv2d_5_tf.h
592=COMPONENTS 4
637=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
638=HOOK MAIN
639=BIND conv2d_5_tf
640=BIND conv2d_5_tf1
641=SAVE conv2d_6_tf1
642=WIDTH conv2d_5_tf.w
643=HEIGHT conv2d_5_tf.h
644=COMPONENTS 4
689=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
690=HOOK MAIN
691=BIND conv2d_6_tf
692=BIND conv2d_6_tf1
693=SAVE conv2d_7_tf
694=WIDTH conv2d_6_tf.w
695=HEIGHT conv2d_6_tf.h
696=COMPONENTS 4
741=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-4x3x3x16
742=HOOK MAIN
743=BIND conv2d_6_tf
744=BIND conv2d_6_tf1
745=SAVE conv2d_7_tf1
746=WIDTH conv2d_6_tf.w
747=HEIGHT conv2d_6_tf.h
748=COMPONENTS 4
793=DESC Anime4K-v4.0-Restore-CNN-(VL)-Conv-3x1x1x112
794=HOOK MAIN
795=BIND MAIN
796=BIND conv2d_1_tf
797=BIND conv2d_1_tf1
798=BIND conv2d_2_tf
799=BIND conv2d_2_tf1
800=BIND conv2d_3_tf
801=BIND conv2d_3_tf1
802=BIND conv2d_4_tf
803=BIND conv2d_4_tf1
804=BIND conv2d_5_tf
805=BIND conv2d_5_tf1
806=BIND conv2d_6_tf
807=BIND conv2d_6_tf1
808=BIND conv2d_7_tf
809=BIND conv2d_7_tf1
810=SAVE MAIN
811=WIDTH conv2d_1_tf.w
812=HEIGHT conv2d_1_tf.h
