25=DESC Anime4K-v3.2-AutoDownscalePre-x4
26=HOOK MAIN
27=BIND HOOKED
28=BIND NATIVE
29=WHEN OUTPUT.w NATIVE.w / 4.0 < OUTPUT.h NATIVE.h / 4.0 < * OUTPUT.w NATIVE.w / 2.4 > OUTPUT.h NATIVE.h / 2.4 > * *
30=WIDTH OUTPUT.w 2 /
31=HEIGHT OUTPUT.h 2 /
