23=DESC Anime4K-v4.0-De-Ring-Compute-Statistics
24=HOOK MAIN
25=BIND HOOKED
26=SAVE STATSMAX
27=COMPONENTS 1
49=DESC Anime4K-v4.0-De-Ring-Compute-Statistics
50=HOOK MAIN
51=BIND HOOKED
52=BIND STATSMAX
53=SAVE STATSMAX
54=COMPONENTS 1
72=DESC Anime4K-v4.0-De-Ring-Clamp
73=HOOK PREKERNEL
74=BIND HOOKED
75=BIND STATSMAX
