23=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x3
24=HOOK MAIN
25=BIND MAIN
26=SAVE conv2d_tf
27=WIDTH MAIN.w
28=HEIGHT MAIN.h
29=COMPONENTS 4
30=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
45=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x3
46=HOOK MAIN
47=BIND MAIN
48=SAVE conv2d_tf1
49=WIDTH MAIN.w
50=HEIGHT MAIN.h
51=COMPONENTS 4
52=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
67=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
68=HOOK MAIN
69=BIND conv2d_tf
70=BIND conv2d_tf1
71=SAVE conv2d_1_tf
72=WIDTH conv2d_tf.w
73=HEIGHT conv2d_tf.h
74=COMPONENTS 4
75=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
120=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
121=HOOK MAIN
122=BIND conv2d_tf
123=BIND conv2d_tf1
124=SAVE conv2d_1_tf1
125=WIDTH conv2d_tf.w
126=HEIGHT conv2d_tf.h
127=COMPONENTS 4
128=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
173=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
174=HOOK MAIN
175=BIND conv2d_1_tf
176=BIND conv2d_1_tf1
177=SAVE conv2d_2_tf
178=WIDTH conv2d_1_tf.w
179=HEIGHT conv2d_1_tf.h
180=COMPONENTS 4
181=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
226=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
227=HOOK MAIN
228=BIND conv2d_1_tf
229=BIND conv2d_1_tf1
230=SAVE conv2d_2_tf1
231=WIDTH conv2d_1_tf.w
232=HEIGHT conv2d_1_tf.h
233=COMPONENTS 4
234=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
279=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
280=HOOK MAIN
281=BIND conv2d_2_tf
282=BIND conv2d_2_tf1
283=SAVE conv2d_3_tf
284=WIDTH conv2d_2_tf.w
285=HEIGHT conv2d_2_tf.h
286=COMPONENTS 4
287=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
332=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
333=HOOK MAIN
334=BIND conv2d_2_tf
335=BIND conv2d_2_tf1
336=SAVE conv2d_3_tf1
337=WIDTH conv2d_2_tf.w
338=HEIGHT conv2d_2_tf.h
339=COMPONENTS 4
340=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
385=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
386=HOOK MAIN
387=BIND conv2d_3_tf
388=BIND conv2d_3_tf1
389=SAVE conv2d_4_tf
390=WIDTH conv2d_3_tf.w
391=HEIGHT conv2d_3_tf.h
392=COMPONENTS 4
393=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
438=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
439=HOOK MAIN
440=BIND conv2d_3_tf
441=BIND conv2d_3_tf1
442=SAVE conv2d_4_tf1
443=WIDTH conv2d_3_tf.w
444=HEIGHT conv2d_3_tf.h
445=COMPONENTS 4
446=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
491=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
492=HOOK MAIN
493=BIND conv2d_4_tf
494=BIND conv2d_4_tf1
495=SAVE conv2d_5_tf
496=WIDTH conv2d_4_tf.w
497=HEIGHT conv2d_4_tf.h
498=COMPONENTS 4
499=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
544=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
545=HOOK MAIN
546=BIND conv2d_4_tf
547=BIND conv2d_4_tf1
548=SAVE conv2d_5_tf1
549=WIDTH conv2d_4_tf.w
550=HEIGHT conv2d_4_tf.h
551=COMPONENTS 4
552=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
597=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
598=HOOK MAIN
599=BIND conv2d_5_tf
600=BIND conv2d_5_tf1
601=SAVE conv2d_6_tf
602=WIDTH conv2d_5_tf.w
603=HEIGHT conv2d_5_tf.h
604=COMPONENTS 4
605=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
650=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x3x3x16
651=HOOK MAIN
652=BIND conv2d_5_tf
653=BIND conv2d_5_tf1
654=SAVE conv2d_6_tf1
655=WIDTH conv2d_5_tf.w
656=HEIGHT conv2d_5_tf.h
657=COMPONENTS 4
658=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
703=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x1x1x112
704=HOOK MAIN
705=BIND conv2d_tf
706=BIND conv2d_tf1
707=BIND conv2d_1_tf
708=BIND conv2d_1_tf1
709=BIND conv2d_2_tf
710=BIND conv2d_2_tf1
711=BIND conv2d_3_tf
712=BIND conv2d_3_tf1
713=BIND conv2d_4_tf
714=BIND conv2d_4_tf1
715=BIND conv2d_5_tf
716=BIND conv2d_5_tf1
717=BIND conv2d_6_tf
718=BIND conv2d_6_tf1
719=SAVE conv2d_last_tf
720=WIDTH conv2d_tf.w
721=HEIGHT conv2d_tf.h
722=COMPONENTS 4
723=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
784=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x1x1x112
785=HOOK MAIN
786=BIND conv2d_tf
787=BIND conv2d_tf1
788=BIND conv2d_1_tf
789=BIND conv2d_1_tf1
790=BIND conv2d_2_tf
791=BIND conv2d_2_tf1
792=BIND conv2d_3_tf
793=BIND conv2d_3_tf1
794=BIND conv2d_4_tf
795=BIND conv2d_4_tf1
796=BIND conv2d_5_tf
797=BIND conv2d_5_tf1
798=BIND conv2d_6_tf
799=BIND conv2d_6_tf1
800=SAVE conv2d_last_tf1
801=WIDTH conv2d_tf.w
802=HEIGHT conv2d_tf.h
803=COMPONENTS 4
804=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
865=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Conv-4x1x1x112
866=HOOK MAIN
867=BIND conv2d_tf
868=BIND conv2d_tf1
869=BIND conv2d_1_tf
870=BIND conv2d_1_tf1
871=BIND conv2d_2_tf
872=BIND conv2d_2_tf1
873=BIND conv2d_3_tf
874=BIND conv2d_3_tf1
875=BIND conv2d_4_tf
876=BIND conv2d_4_tf1
877=BIND conv2d_5_tf
878=BIND conv2d_5_tf1
879=BIND conv2d_6_tf
880=BIND conv2d_6_tf1
881=SAVE conv2d_last_tf2
882=WIDTH conv2d_tf.w
883=HEIGHT conv2d_tf.h
884=COMPONENTS 4
885=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
946=DESC Anime4K-v3.2-Upscale-CNN-x2-(VL)-Depth-to-Space
947=HOOK MAIN
948=BIND MAIN
949=BIND conv2d_last_tf
950=BIND conv2d_last_tf1
951=BIND conv2d_last_tf2
952=SAVE MAIN
953=WIDTH conv2d_last_tf.w 2 *
954=HEIGHT conv2d_last_tf.h 2 *
955=WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *
