 
                                                   
 
                                                                                                                                                                                                                    
                                                                                                          
 
                                                   
 
kotlin.code.style=official
android.useAndroidX=true
org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
                                                                                       
version.name=1.0.10
                                                        
package.version=1.0.10
org.gradle.caching=true
org.gradle.configuration-cache=true
                                                                      
                                                                                       
                                                                                                                              
android.version.code=7
                                                                                  
                                                                          
                                                                                             
                                                                  
                                         
android.compile.sdk=37
android.min.sdk=27
                            
jvm.toolchain.vendor=jetbrains
jvm.toolchain.version=21
