name = "wynime-bangumi-broker"
main = "src/index.ts"
compatibility_date = "2026-09-08"

[[durable_objects.bindings]]
name = "REPLAY_MARKERS"
class_name = "ReplayMarker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReplayMarker"]

[vars]
BANGUMI_AUTHORIZE_URL = "https://bgm.tv/oauth/authorize"
BANGUMI_TOKEN_URL = "https://bgm.tv/oauth/access_token"
APP_LINK_HOST = "wynime-bangumi-broker.wzhou785.workers.dev"
ANDROID_PACKAGE_NAME = "io.github.william12233.wynime"
ANDROID_CERT_SHA256 = "32:FA:14:32:9B:DA:4D:DD:9C:2F:9D:6B:E9:73:EF:70:A4:27:2B:56:30:AB:BA:B7:14:FF:50:F0:F6:25:4B:53"
