/*
 * Copyright (C) 2024-2025 OpenAni and contributors.
 *
 * 此源代码的使用受 GNU AFFERO GENERAL PUBLIC LICENSE version 3 许可证的约束, 可以在以下链接找到该许可证.
 * Use of this source code is governed by the GNU AGPLv3 license, which can be found at the following link.
 *
 * https://github.com/open-ani/ani/blob/main/LICENSE
 */

// @formatter:off
@file:Suppress("RedundantVisibilityModifier")

// Generated by me.him188.ani.utils.bbcode.BBCodeTestGenerator
package me.him188.ani.utils.bbcode

import kotlin.test.Test

public class GenBBSpacesTest : BBCodeParserTestHelper() {
    @Test
    public fun parse137138206() {
        BBCode.parse("[b]Hello World![/b]")
        .run {
            assertText(elements.at(0), value="Hello World!", bold=true)
        }
    }

    @Test
    public fun parse2052759877() {
        BBCode.parse("[b][/b]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse842178951() {
        BBCode.parse("[b] [/b]")
        .run {
            assertText(elements.at(0), value=" ", bold=true)
        }
    }

    @Test
    public fun parse1488478815() {
        BBCode.parse("[b] /[][/]Hello [/b]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", bold=true)
        }
    }

    @Test
    public fun parse1704405026() {
        BBCode.parse("[B]Hello World![/B]")
        .run {
            assertText(elements.at(0), value="Hello World!", bold=true)
        }
    }

    @Test
    public fun parse1136626053() {
        BBCode.parse("[B][/B]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse822473337() {
        BBCode.parse("[B] [/B]")
        .run {
            assertText(elements.at(0), value=" ", bold=true)
        }
    }

    @Test
    public fun parse1553193377() {
        BBCode.parse("[B] /[][/]Hello [/B]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", bold=true)
        }
    }

    @Test
    public fun parse1473290132() {
        BBCode.parse("[i]Hello World![/i]")
        .run {
            assertText(elements.at(0), value="Hello World!", italic=true)
        }
    }

    @Test
    public fun parse2041803145() {
        BBCode.parse("[i][/i]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1075379737() {
        BBCode.parse("[i] [/i]")
        .run {
            assertText(elements.at(0), value=" ", italic=true)
        }
    }

    @Test
    public fun parse127856769() {
        BBCode.parse("[i] /[][/]Hello [/i]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", italic=true)
        }
    }

    @Test
    public fun parse980133932() {
        BBCode.parse("[I]Hello World![/I]")
        .run {
            assertText(elements.at(0), value="Hello World!", italic=true)
        }
    }

    @Test
    public fun parse1337030327() {
        BBCode.parse("[I][/I]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1554935271() {
        BBCode.parse("[I] [/I]")
        .run {
            assertText(elements.at(0), value=" ", italic=true)
        }
    }

    @Test
    public fun parse1125438335() {
        BBCode.parse("[I] /[][/]Hello [/I]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", italic=true)
        }
    }

    @Test
    public fun parse1901643140() {
        BBCode.parse("[u]Hello World![/u]")
        .run {
            assertText(elements.at(0), value="Hello World!", underline=true)
        }
    }

    @Test
    public fun parse1698252961() {
        BBCode.parse("[u][/u]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1159477607() {
        BBCode.parse("[u] [/u]")
        .run {
            assertText(elements.at(0), value=" ", underline=true)
        }
    }

    @Test
    public fun parse1671584257() {
        BBCode.parse("[u] /[][/]Hello [/u]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", underline=true)
        }
    }

    @Test
    public fun parse60099908() {
        BBCode.parse("[U]Hello World![/U]")
        .run {
            assertText(elements.at(0), value="Hello World!", underline=true)
        }
    }

    @Test
    public fun parse1680580511() {
        BBCode.parse("[U][/U]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse505174681() {
        BBCode.parse("[U] [/U]")
        .run {
            assertText(elements.at(0), value=" ", underline=true)
        }
    }

    @Test
    public fun parse418289153() {
        BBCode.parse("[U] /[][/]Hello [/U]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", underline=true)
        }
    }

    @Test
    public fun parse92501504() {
        BBCode.parse("[s]Hello World![/s]")
        .run {
            assertText(elements.at(0), value="Hello World!", strikethrough=true)
        }
    }

    @Test
    public fun parse1755511325() {
        BBCode.parse("[s][/s]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1360482265() {
        BBCode.parse("[s] [/s]")
        .run {
            assertText(elements.at(0), value=" ", strikethrough=true)
        }
    }

    @Test
    public fun parse17359423() {
        BBCode.parse("[s] /[][/]Hello [/s]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", strikethrough=true)
        }
    }

    @Test
    public fun parse1934044736() {
        BBCode.parse("[S]Hello World![/S]")
        .run {
            assertText(elements.at(0), value="Hello World!", strikethrough=true)
        }
    }

    @Test
    public fun parse1623322147() {
        BBCode.parse("[S][/S]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1269832743() {
        BBCode.parse("[S] [/S]")
        .run {
            assertText(elements.at(0), value=" ", strikethrough=true)
        }
    }

    @Test
    public fun parse1270654527() {
        BBCode.parse("[S] /[][/]Hello [/S]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", strikethrough=true)
        }
    }

    @Test
    public fun parse1502622152() {
        BBCode.parse("[url]Hello World![/url]")
        .run {
            assertText(elements.at(0), value="Hello World!", jumpUrl="Hello World!")
        }
    }

    @Test
    public fun parse1108237035() {
        BBCode.parse("[url][/url]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse367631961() {
        BBCode.parse("[url] [/url]")
        .run {
            assertText(elements.at(0), value=" ", jumpUrl=" ")
        }
    }

    @Test
    public fun parse493385023() {
        BBCode.parse("[url] /[][/]Hello [/url]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", jumpUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse24140296() {
        BBCode.parse("[URL]Hello World![/URL]")
        .run {
            assertText(elements.at(0), value="Hello World!", jumpUrl="Hello World!")
        }
    }

    @Test
    public fun parse874361643() {
        BBCode.parse("[URL][/URL]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1736981081() {
        BBCode.parse("[URL] [/URL]")
        .run {
            assertText(elements.at(0), value=" ", jumpUrl=" ")
        }
    }

    @Test
    public fun parse1934639423() {
        BBCode.parse("[URL] /[][/]Hello [/URL]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", jumpUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse1176497952() {
        BBCode.parse("[img]Hello World![/img]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!")
        }
    }

    @Test
    public fun parse505710013() {
        BBCode.parse("[img][/img]")
        .run {
            assertImage(elements.at(0), imageUrl="")
        }
    }

    @Test
    public fun parse1885754585() {
        BBCode.parse("[img] [/img]")
        .run {
            assertImage(elements.at(0), imageUrl=" ")
        }
    }

    @Test
    public fun parse1015657025() {
        BBCode.parse("[img] /[][/]Hello [/img]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse301983904() {
        BBCode.parse("[IMG]Hello World![/IMG]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!")
        }
    }

    @Test
    public fun parse739585405() {
        BBCode.parse("[IMG][/IMG]")
        .run {
            assertImage(elements.at(0), imageUrl="")
        }
    }

    @Test
    public fun parse1039863591() {
        BBCode.parse("[IMG] [/IMG]")
        .run {
            assertImage(elements.at(0), imageUrl=" ")
        }
    }

    @Test
    public fun parse425597375() {
        BBCode.parse("[IMG] /[][/]Hello [/IMG]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse872695250() {
        BBCode.parse("[quote]Hello World![/quote]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value="Hello World!")
            }
        }
    }

    @Test
    public fun parse470600465() {
        BBCode.parse("[quote][/quote]")
        .run {
            assertQuote(elements.at(0)) {
                kotlin.test.assertEquals(0, elements.size)
            }
        }
    }

    @Test
    public fun parse1788776377() {
        BBCode.parse("[quote] [/quote]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value=" ")
            }
        }
    }

    @Test
    public fun parse1294424479() {
        BBCode.parse("[quote] /[][/]Hello [/quote]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value=" /[][/]Hello ")
            }
        }
    }

    @Test
    public fun parse993940078() {
        BBCode.parse("[QUOTE]Hello World![/QUOTE]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value="Hello World!")
            }
        }
    }

    @Test
    public fun parse1148415151() {
        BBCode.parse("[QUOTE][/QUOTE]")
        .run {
            assertQuote(elements.at(0)) {
                kotlin.test.assertEquals(0, elements.size)
            }
        }
    }

    @Test
    public fun parse1474245561() {
        BBCode.parse("[QUOTE] [/QUOTE]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value=" ")
            }
        }
    }

    @Test
    public fun parse1660890527() {
        BBCode.parse("[QUOTE] /[][/]Hello [/QUOTE]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value=" /[][/]Hello ")
            }
        }
    }

    @Test
    public fun parse1141258730() {
        BBCode.parse("[code]Hello World![/code]")
        .run {
            assertText(elements.at(0), value="Hello World!", code=true)
        }
    }

    @Test
    public fun parse496956199() {
        BBCode.parse("[code][/code]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1670130897() {
        BBCode.parse("[code] [/code]")
        .run {
            assertText(elements.at(0), value=" ", code=true)
        }
    }

    @Test
    public fun parse1274924885() {
        BBCode.parse("[code] /[][/]Hello [/code]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", code=true)
        }
    }

    @Test
    public fun parse402209258() {
        BBCode.parse("[CODE]Hello World![/CODE]")
        .run {
            assertText(elements.at(0), value="Hello World!", code=true)
        }
    }

    @Test
    public fun parse2001072935() {
        BBCode.parse("[CODE][/CODE]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1969241297() {
        BBCode.parse("[CODE] [/CODE]")
        .run {
            assertText(elements.at(0), value=" ", code=true)
        }
    }

    @Test
    public fun parse1794490197() {
        BBCode.parse("[CODE] /[][/]Hello [/CODE]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", code=true)
        }
    }

    @Test
    public fun parse995222602() {
        BBCode.parse("[mask]Hello World![/mask]")
        .run {
            assertText(elements.at(0), value="Hello World!", mask=true)
        }
    }

    @Test
    public fun parse276603911() {
        BBCode.parse("[mask][/mask]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1130804845() {
        BBCode.parse("[mask] [/mask]")
        .run {
            assertText(elements.at(0), value=" ", mask=true)
        }
    }

    @Test
    public fun parse1772059667() {
        BBCode.parse("[mask] /[][/]Hello [/mask]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", mask=true)
        }
    }

    @Test
    public fun parse256173130() {
        BBCode.parse("[MASK]Hello World![/MASK]")
        .run {
            assertText(elements.at(0), value="Hello World!", mask=true)
        }
    }

    @Test
    public fun parse1780720647() {
        BBCode.parse("[MASK][/MASK]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse831694445() {
        BBCode.parse("[MASK] [/MASK]")
        .run {
            assertText(elements.at(0), value=" ", mask=true)
        }
    }

    @Test
    public fun parse2003342317() {
        BBCode.parse("[MASK] /[][/]Hello [/MASK]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", mask=true)
        }
    }

    @Test
    public fun parse1038614614() {
        BBCode.parse("[center]Hello World![/center]")
        .run {
            assertText(elements.at(0), value="Hello World!", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse2146736551() {
        BBCode.parse("[center][/center]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse440500865() {
        BBCode.parse("[center] [/center]")
        .run {
            assertText(elements.at(0), value=" ", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse455848923() {
        BBCode.parse("[center] /[][/]Hello [/center]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse554139562() {
        BBCode.parse("[CENTER]Hello World![/CENTER]")
        .run {
            assertText(elements.at(0), value="Hello World!", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse1640883801() {
        BBCode.parse("[CENTER][/CENTER]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse1076258175() {
        BBCode.parse("[CENTER] [/CENTER]")
        .run {
            assertText(elements.at(0), value=" ", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse1773024293() {
        BBCode.parse("[CENTER] /[][/]Hello [/CENTER]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse77622314() {
        BBCode.parse("[left]Hello World![/left]")
        .run {
            assertText(elements.at(0), value="Hello World!", align=RichElement.Text.Align.LEFT)
        }
    }

    @Test
    public fun parse721321063() {
        BBCode.parse("[left][/left]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse204977891() {
        BBCode.parse("[left] [/left]")
        .run {
            assertText(elements.at(0), value=" ", align=RichElement.Text.Align.LEFT)
        }
    }

    @Test
    public fun parse128400393() {
        BBCode.parse("[left] /[][/]Hello [/left]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", align=RichElement.Text.Align.LEFT)
        }
    }

    @Test
    public fun parse661427158() {
        BBCode.parse("[LEFT]Hello World![/LEFT]")
        .run {
            assertText(elements.at(0), value="Hello World!", align=RichElement.Text.Align.LEFT)
        }
    }

    @Test
    public fun parse2069529497() {
        BBCode.parse("[LEFT][/LEFT]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse94132509() {
        BBCode.parse("[LEFT] [/LEFT]")
        .run {
            assertText(elements.at(0), value=" ", align=RichElement.Text.Align.LEFT)
        }
    }

    @Test
    public fun parse647965705() {
        BBCode.parse("[LEFT] /[][/]Hello [/LEFT]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", align=RichElement.Text.Align.LEFT)
        }
    }

    @Test
    public fun parse605006574() {
        BBCode.parse("[right]Hello World![/right]")
        .run {
            assertText(elements.at(0), value="Hello World!", align=RichElement.Text.Align.RIGHT)
        }
    }

    @Test
    public fun parse388609071() {
        BBCode.parse("[right][/right]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse404159417() {
        BBCode.parse("[right] [/right]")
        .run {
            assertText(elements.at(0), value=" ", align=RichElement.Text.Align.RIGHT)
        }
    }

    @Test
    public fun parse660384353() {
        BBCode.parse("[right] /[][/]Hello [/right]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", align=RichElement.Text.Align.RIGHT)
        }
    }

    @Test
    public fun parse1823325394() {
        BBCode.parse("[RIGHT]Hello World![/RIGHT]")
        .run {
            assertText(elements.at(0), value="Hello World!", align=RichElement.Text.Align.RIGHT)
        }
    }

    @Test
    public fun parse2007624687() {
        BBCode.parse("[RIGHT][/RIGHT]")
        .run {
            kotlin.test.assertEquals(0, elements.size)
        }
    }

    @Test
    public fun parse89628601() {
        BBCode.parse("[RIGHT] [/RIGHT]")
        .run {
            assertText(elements.at(0), value=" ", align=RichElement.Text.Align.RIGHT)
        }
    }

    @Test
    public fun parse293918305() {
        BBCode.parse("[RIGHT] /[][/]Hello [/RIGHT]")
        .run {
            assertText(elements.at(0), value=" /[][/]Hello ", align=RichElement.Text.Align.RIGHT)
        }
    }

    @Test
    public fun parse1308903400() {
        BBCode.parse("[img=300,200]Hello World![/img=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!", width=300, height=200)
        }
    }

    @Test
    public fun parse314635787() {
        BBCode.parse("[img=300,200][/img=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl="", width=300, height=200)
        }
    }

    @Test
    public fun parse743621543() {
        BBCode.parse("[img=300,200] [/img=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" ", width=300, height=200)
        }
    }

    @Test
    public fun parse50537791() {
        BBCode.parse("[img=300,200] /[][/]Hello [/img=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ", width=300, height=200)
        }
    }

    @Test
    public fun parse181801000() {
        BBCode.parse("[IMG=300,200]Hello World![/IMG=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!", width=300, height=200)
        }
    }

    @Test
    public fun parse1251873205() {
        BBCode.parse("[IMG=300,200][/IMG=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl="", width=300, height=200)
        }
    }

    @Test
    public fun parse866256807() {
        BBCode.parse("[IMG=300,200] [/IMG=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" ", width=300, height=200)
        }
    }

    @Test
    public fun parse664604991() {
        BBCode.parse("[IMG=300,200] /[][/]Hello [/IMG=300,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ", width=300, height=200)
        }
    }

    @Test
    public fun parse1205296268() {
        BBCode.parse("[img=300]Hello World![/img=300]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!")
        }
    }

    @Test
    public fun parse1645990935() {
        BBCode.parse("[img=300][/img=300]")
        .run {
            assertImage(elements.at(0), imageUrl="")
        }
    }

    @Test
    public fun parse605928295() {
        BBCode.parse("[img=300] [/img=300]")
        .run {
            assertImage(elements.at(0), imageUrl=" ")
        }
    }

    @Test
    public fun parse485058943() {
        BBCode.parse("[img=300] /[][/]Hello [/img=300]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse1897030732() {
        BBCode.parse("[IMG=300]Hello World![/IMG=300]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!")
        }
    }

    @Test
    public fun parse1193280425() {
        BBCode.parse("[IMG=300][/IMG=300]")
        .run {
            assertImage(elements.at(0), imageUrl="")
        }
    }

    @Test
    public fun parse1349128039() {
        BBCode.parse("[IMG=300] [/IMG=300]")
        .run {
            assertImage(elements.at(0), imageUrl=" ")
        }
    }

    @Test
    public fun parse1890993535() {
        BBCode.parse("[IMG=300] /[][/]Hello [/IMG=300]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse869897014() {
        BBCode.parse("[img=,200]Hello World![/img=,200]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!")
        }
    }

    @Test
    public fun parse285905927() {
        BBCode.parse("[img=,200][/img=,200]")
        .run {
            assertImage(elements.at(0), imageUrl="")
        }
    }

    @Test
    public fun parse1907075883() {
        BBCode.parse("[img=,200] [/img=,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" ")
        }
    }

    @Test
    public fun parse204343675() {
        BBCode.parse("[img=,200] /[][/]Hello [/img=,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ")
        }
    }

    @Test
    public fun parse235597622() {
        BBCode.parse("[IMG=,200]Hello World![/IMG=,200]")
        .run {
            assertImage(elements.at(0), imageUrl="Hello World!")
        }
    }

    @Test
    public fun parse1278449657() {
        BBCode.parse("[IMG=,200][/IMG=,200]")
        .run {
            assertImage(elements.at(0), imageUrl="")
        }
    }

    @Test
    public fun parse327881451() {
        BBCode.parse("[IMG=,200] [/IMG=,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" ")
        }
    }

    @Test
    public fun parse1950256709() {
        BBCode.parse("[IMG=,200] /[][/]Hello [/IMG=,200]")
        .run {
            assertImage(elements.at(0), imageUrl=" /[][/]Hello ")
        }
    }
}


// @formatter:on
