/*
 * Copyright (C) 2024-2025 OpenAni and contributors.
 *
 * 此源代码的使用受 GNU AFFERO GENERAL PUBLIC LICENSE version 3 许可证的约束, 可以在以下链接找到该许可证.
 * Use of this source code is governed by the GNU AGPLv3 license, which can be found at the following link.
 *
 * https://github.com/open-ani/ani/blob/main/LICENSE
 */

// @formatter:off
@file:Suppress("RedundantVisibilityModifier")

// Generated by me.him188.ani.utils.bbcode.BBCodeTestGenerator
package me.him188.ani.utils.bbcode

import kotlin.test.Test

public class GenBBNestedContextTest : BBCodeParserTestHelper() {
    @Test
    public fun parse1377236079() {
        BBCode.parse("[b]Hello [i]World![/i][/b]")
        .run {
            assertText(elements.at(0), value="Hello ", bold=true)
            assertText(elements.at(1), value="World!", italic=true, bold=true)
        }
    }

    @Test
    public fun parse1607063481() {
        BBCode.parse("[url=https://example.com]Hello [b][i]World![/i][/b][/url]")
        .run {
            assertText(elements.at(0), value="Hello ", jumpUrl="https://example.com")
            assertText(elements.at(1), value="World!", jumpUrl="https://example.com", italic=true,
                    bold=true)
        }
    }

    @Test
    public fun parse608569134() {
        BBCode.parse("[url=https://example.com]Hello [b][i]World![/i][/b] [b][i]Again![/i][/b][/url]")
        .run {
            assertText(elements.at(0), value="Hello ", jumpUrl="https://example.com")
            assertText(elements.at(1), value="World!", jumpUrl="https://example.com", italic=true,
                    bold=true)
            assertText(elements.at(2), value=" ", jumpUrl="https://example.com")
            assertText(elements.at(3), value="Again!", jumpUrl="https://example.com", italic=true,
                    bold=true)
        }
    }

    @Test
    public fun parse689343298() {
        BBCode.parse("[quote]Hello [b][i]World![/i][/b][/quote]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value="Hello ")
                assertText(elements.at(1), value="World!", italic=true, bold=true)
            }
        }
    }

    @Test
    public fun parse822894058() {
        BBCode.parse("[size=1][size=2]Hello World![/size][/size]")
        .run {
            assertText(elements.at(0), value="Hello World!", size=2)
        }
    }

    @Test
    public fun parse2127590386() {
        BBCode.parse("[size=1]Hello[size=2]World[/size]![/size]")
        .run {
            assertText(elements.at(0), value="Hello", size=1)
            assertText(elements.at(1), value="World", size=2)
            assertText(elements.at(2), value="!", size=1)
        }
    }

    @Test
    public fun parse1668662357() {
        BBCode.parse("[size=1]Hello[b][size=2]World[/size]![/b][/size]")
        .run {
            assertText(elements.at(0), value="Hello", size=1)
            assertText(elements.at(1), value="World", size=2, bold=true)
            assertText(elements.at(2), value="!", size=1, bold=true)
        }
    }

    @Test
    public fun parse815976454() {
        BBCode.parse("[color=red][size=1]Hello[b][size=2]World[/size]![/b][/size][/color]")
        .run {
            assertText(elements.at(0), value="Hello", size=1, color="red")
            assertText(elements.at(1), value="World", size=2, color="red", bold=true)
            assertText(elements.at(2), value="!", size=1, color="red", bold=true)
        }
    }

    @Test
    public fun parse14804774() {
        BBCode.parse("[center]Hello [b][i]World![/i][/b][/center]")
        .run {
            assertText(elements.at(0), value="Hello ", align=RichElement.Text.Align.CENTER)
            assertText(elements.at(1), value="World!", italic=true, bold=true,
                    align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse227476899() {
        BBCode.parse("[center]Hello[left]World[/left]![/center]")
        .run {
            assertText(elements.at(0), value="Hello", align=RichElement.Text.Align.CENTER)
            assertText(elements.at(1), value="World", align=RichElement.Text.Align.LEFT)
            assertText(elements.at(2), value="!", align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse1546688906() {
        BBCode.parse("[center][url=https://example.com]Hello World![/url][/center]")
        .run {
            assertText(elements.at(0), value="Hello World!", jumpUrl="https://example.com",
                    align=RichElement.Text.Align.CENTER)
        }
    }

    @Test
    public fun parse1982811943() {
        BBCode.parse("[center][img]https://example.com/image.png[/img][/center]")
        .run {
            assertImage(elements.at(0), imageUrl="https://example.com/image.png")
        }
    }

    @Test
    public fun parse971327987() {
        BBCode.parse("[center][quote]Hello World![/quote][/center]")
        .run {
            assertQuote(elements.at(0)) {
                assertText(elements.at(0), value="Hello World!")
            }
        }
    }

    @Test
    public fun parse679287293() {
        BBCode.parse("[b][center]Hello World![/center][/b]")
        .run {
            assertText(elements.at(0), value="Hello World!", bold=true,
                    align=RichElement.Text.Align.CENTER)
        }
    }
}


// @formatter:on
