target 'Animeko' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'application', :path => '../shared/application'

  pod 'Sentry', '~> 8.49.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end
end
